version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888" 
      - "3888:3888"
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOOKEEPER_CLIENT_PORT=2181


  clickhouse-1:
    image: yandex/clickhouse-server
    container_name: clickhouse-1
    hostname: clickhouse-1
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./clickhouse1/data:/var/lib/clickhouse/
      - ./clickhouse1/log:/var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
    ulimits:
      nofile: 262144
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    depends_on:
      - zookeeper

  clickhouse-2:
    image: yandex/clickhouse-server
    container_name: clickhouse-2
    hostname: clickhouse-2
    ports:
      - "9001:9000"
      - "8124:8123"
    volumes:
      - ./clickhouse2/data:/var/lib/clickhouse/
      - ./clickhouse2/log:/var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
    ulimits:
      nofile: 262144
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    depends_on:
      - zookeeper

